package com.example.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class TransferTransaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_transaction.id
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_transaction.from_account
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    private Integer fromAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_transaction.to_account
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    private Integer toAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_transaction.transaction_id
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    private Long transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_transaction.money
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_transaction.process_status
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    private String processStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_transaction.create_time
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_transaction.update_time
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_transaction.id
     *
     * @return the value of transfer_transaction.id
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_transaction.id
     *
     * @param id the value for transfer_transaction.id
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_transaction.from_account
     *
     * @return the value of transfer_transaction.from_account
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public Integer getFromAccount() {
        return fromAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_transaction.from_account
     *
     * @param fromAccount the value for transfer_transaction.from_account
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public void setFromAccount(Integer fromAccount) {
        this.fromAccount = fromAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_transaction.to_account
     *
     * @return the value of transfer_transaction.to_account
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public Integer getToAccount() {
        return toAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_transaction.to_account
     *
     * @param toAccount the value for transfer_transaction.to_account
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public void setToAccount(Integer toAccount) {
        this.toAccount = toAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_transaction.transaction_id
     *
     * @return the value of transfer_transaction.transaction_id
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public Long getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_transaction.transaction_id
     *
     * @param transactionId the value for transfer_transaction.transaction_id
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_transaction.money
     *
     * @return the value of transfer_transaction.money
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_transaction.money
     *
     * @param money the value for transfer_transaction.money
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_transaction.process_status
     *
     * @return the value of transfer_transaction.process_status
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_transaction.process_status
     *
     * @param processStatus the value for transfer_transaction.process_status
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus == null ? null : processStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_transaction.create_time
     *
     * @return the value of transfer_transaction.create_time
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_transaction.create_time
     *
     * @param createTime the value for transfer_transaction.create_time
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_transaction.update_time
     *
     * @return the value of transfer_transaction.update_time
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_transaction.update_time
     *
     * @param updateTime the value for transfer_transaction.update_time
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}