package com.example.demo.mapper;

import com.example.demo.model.TransferTransaction;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.transaction.annotation.Transactional;

@Mapper
public interface TransferTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_transaction
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_transaction
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    int insert(TransferTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_transaction
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    int insertSelective(TransferTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_transaction
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    TransferTransaction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_transaction
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    int updateByPrimaryKeySelective(TransferTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_transaction
     *
     * @mbg.generated Tue Dec 10 17:31:52 CST 2024
     */
    int updateByPrimaryKey(TransferTransaction record);

    @Transactional(readOnly = true)
    TransferTransaction selectByTransactionId(Long transactionId);

    @Delete("delete from transfer_transaction where transaction_id= #{transactionId}")
    int deleteByTransactionId(Long transactionId);
}